name: build

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install devscripts debhelper -y
      - name: Build package
        run: |
          debuild -i -us -uc -b
          mv ../*.deb .
      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          path: '*.deb'
